trigger:
  - main
  - refs/pull/*/merge

parameters:
  - name: yamlLinterList
    type: object
    default:
      - path: .
        lintConfigurationPath: .yamllint
      - path: kustomizations-folder
        lintConfigurationPath: .yamllint_kustomize.yaml
  - name: kustomizeCheckList
    type: object
    default:
      - path: kustomizations-folder

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: validateFilesStage
    displayName: "Validate YAML and Kustomize"
    jobs:
      - job: check
        displayName: "Run Linters in Docker"
        timeoutInMinutes: 10
        steps:

          - checkout: self

          - task: Docker@2
            displayName: Build Docker Image (yamllint + kustomize)
            inputs:
              command: build
              dockerfile: $(Build.SourcesDirectory)/dockerfile-temp
              repository: yamllinter-local
              tags: $(Build.BuildId)
              buildContext: $(Build.SourcesDirectory)

          # YAML Lint Checks
          - ${{ each yamlLinter in parameters.yamlLinterList }}:
            - script: |
                echo "Running yamllint for ${{ yamlLinter.path }}"
                docker run --rm \
                  -v $(Build.SourcesDirectory):/src \
                  yamllinter-local:$(Build.BuildId) \
                  yamllint -c /src/${{ yamlLinter.lintConfigurationPath }} /src/${{ yamlLinter.path }}
              displayName: Yamllint - ${{ yamlLinter.path }}

          # Kustomize Checks
          - ${{ each kustomizeCheck in parameters.kustomizeCheckList }}:
            - script: |
                echo "Running validate_kustomize.sh on ${{ kustomizeCheck.path }}"
                docker run --rm \
                  -v $(Build.SourcesDirectory):/src \
                  yamllinter-local:$(Build.BuildId) \
                  bash /usr/local/bin/validate_kustomize.sh -d /src/${{ kustomizeCheck.path }}
              displayName: Kustomize Check - ${{ kustomizeCheck.path }}
